# Core configuration
logging.level.io.maestro3=INFO
server.port=8082
private.agent.name=default
private.agent.lock.disabled=true
extended.request.logging.minutes=120
spring.task.scheduling.pool.size=3
internal.task.retry.cron=45 0/1 * * * ?
internal.task.retry.count=5
#max task ttl in minutes
internal.task.retry.ttl=40
internal.task.delay.millis=60000
agent.tomcat.max-native-event-size=2MB
agent.webhook.host=

# M3 Rabbit connection configuration
rabbit.host=localhost
rabbit.username=random_admin
rabbit.password=random_password_UdG3USFZsCGni6kF4Lbo
rabbit.virtual.host=local_vhost
rabbit.port=5672
rabbit.ssl.enabled=false
rabbit.retry.attempts=5
rabbit.retry.initial.interval=500
rabbit.retry.interval.multiplier=2
rabbit.concurrent.private.agent.ownership.consumers.min=1
rabbit.concurrent.private.agent.ownership.consumers.max=1
rabbit.concurrent.private.agent.consumers.min=1
rabbit.concurrent.private.agent.consumers.max=1
rabbit.prefetch.count=5
rabbit.reply.timeout.ms=1800000
rabbit.shutdown.timeout=30000
rabbit.heartbeat=15
rabbit.channel.cache.size=1
rabbit.consecutive.active.trigger=3
rabbit.consecutive.idle.trigger=10
rabbit.start.consumer.min.interval=10000
rabbit.stop.consumer.min.interval=60000

# MongoDB configuration
mongo.db.private.agent.uri=mongodb://user:password@localhost:27017/vmWare-agent?maxPoolSize=10&waitQueueMultiple=5

# General Properties
private.agent.rabbit.m3api.exchange=m3api-vmware-exchange
private.agent.rabbit.m3api.sync.queue=m3api-vmware-sync-queue
private.agent.rabbit.m3api.async.queue=m3api-vmware-async-queue

server.m3api.response.queue.name=vmware-agent-response
server.m3api.access.key=aaaaaaaaaaaaaaaa
server.m3api.secret.key=aaaaaaaaaaaaaaaa

cron.verify.tokens=0 0/12 * * * ?
cron.clean.vapp=45 0/1 * * * ?
cron.update.vdc=30 0/30 * * * ?
cron.healthcheck.organization=0 15/30 * * * ?
cron.update.vapp.template=30 0/7 * * * ?
cron.update.vm=15 0/3 * * * ?
cron.update.disks=45 0/2 * * * ?

cron.update.vsphere.vm=30 0/2 * * * ?
cron.update.vsphere.tags=30 0/15 * * * ?

cron.update.nutanix.vm=30 0/2 * * * ?

cron.update.hyperv.vm=35 0/2 * * * ?

cron.update.amqp.vm=30 0/1 * * * ?
cron.update.amqp.vdc=0 0/3 * * * ?

amqp.describer.retry.count=3

javax.net.ssl.trustStore=
javax.net.ssl.trustStorePassword=

#wizard configuration settings
configuration.wizard.os.image.list.period.month=1
configuration.wizard.os.flavor.default.disk=15360
configuration.wizard.os.image.list.groups=Windows,Ubuntu,Centos,Postgres

#jmx settings
diagnostic.admin.username=admin
diagnostic.admin.password=admin
maestro.prefix=m3agent
spring.mvc.locale=en_US
spring.mvc.locale-resolver=fixed
server.servlet.session.timeout=15m
ui.js.files.multi=false
environment.name=m3privateAgent
server.contextPath=
server.servlet.context-path=


notification.topics=true.#.com.vmware.vcloud.event.vapp.#,true.#.com.vmware.vcloud.event.vm.#,true.#.com.vmware.vcloud.event.vdc.#,true.#.com.vmware.vcloud.event.vappTemplate.#,true.#.com.vmware.vcloud.event.org.#,true.#.com.vmware.vcloud.event.network.#,true.#.com.vmware.vcloud.event.media.#,true.#.com.vmware.vcloud.event.catalogItem.#,	true.#.com.vmware.vcloud.event.catalog.#
notification.queue.name=vcd.notification.queue
vmware.configuration.shapes.preset=mini.1.512.10,small.1.1024.15,medium.2.2048.20,medium_xl.2.4096.30,large.3.4096.50
vsphere.configuration.shapes.preset=mini.1.512.10,small.1.1024.15,medium.2.2048.20,medium_xl.2.4096.30,large.3.4096.50

flag.enable.instances.schedule.describer=true
flag.enable.images.schedule.describer=true

m3.autoconfiguration.bucket.name=none

m3.chef.version=15
m3.chef.env=prod
m3.chef.prefix=m3
m3.chef.conf.url=http:/localhost:8082/chef/conf/
m3.chef.state.url=http:/localhost:8082/chef/state/
m3.chef.cert.url=http:/localhost:8082/chef/cert/
m3.chef.node.name=agent
m3.chef.ini.storage.url=http:/localhost:8082/chef/init/
m3.chef.api.host=http:/localhost:8082/chef/api/
m3.chef.enabled=false
m3.userscripts.enabled=false

